alpha: 1.0
beam_size: 3
cross_coverage: true
d_model: 256
dc: 16
dim_feedforward: 512
dropout: 0.3
early_stopping: false
gat_dropout: 0.1
gat_hidden_dim: null
gat_num_heads: 8
gat_num_layers: 2
growth_rate: 24
learning_rate: 0.5
max_len: 80
milestones:
- 2
- 4
nhead: 4
num_decoder_layers: 1
num_layers: 4
patience: 5
self_coverage: true
temperature: 1.0
use_gat: false
vocab_size: 113
